### PR TITLE
Fix Neighbor bugs

### PR DESCRIPTION
**Pull request by patnorris**
Fixes bugs related to Neighbor creation and deletion. 
Specifically, the protocolActor for the NFid login option wasn't created and thus all calls to the Protocol were anonymous.
In addition, visualized 3D Neighbors wouldn't open when clicked. They now open in a new tab.

To test:
Neighbor creation (as owner and as visitor) as well as deletion (as owner) should work as expected.
Clicking on visualized 3D Neighbors in space should open the space in a new tab.

### CODE REVIEW

**Comment by tiusty** [comment]
Still some weirdness with the 3D visualizaiton:
image

When I zoom forward and backwards the image moves with me
image

**Comment by tiusty** [comment]
When you delete a neighbor the 3D visualization is still there. Not a big deal unless that is easy to fix
image

**Comment by tiusty** [comment]
> When you delete a neighbor the 3D visualization is still there. Not a big deal unless that is easy to fix image

Also the image of the visualization disappears when you are in the neighbor menu

**Comment by tiusty** [comment]
> > When you delete a neighbor the 3D visualization is still there. Not a big deal unless that is easy to fix image
> 
> Also the image of the visualization disappears when you are in the neighbor menu

Actually the weird behvaior of it moving with you happens once you click on the menu bar

**Comment by tiusty** [comment]
> When you delete a neighbor the 3D visualization is still there. Not a big deal unless that is easy to fix image

Same happens for the creation of a space

**Review by tiusty — DISMISSED** [review]
Tested and some weird behaviors with the 3D visualization but I know that is hard so not a big deal if you don't want to address it now

**Comment by patnorris** [comment]
This commit fixes the issue: https://github.com/Bebb-Protocol-and-Apps/PWS/pull/64/commits/c151dbcafc8fb265889ebf7e5832292e27b09240 I opted for a simple solution by removing the 3D Neighbor visualizations when the menu is opened. Does this seem good to you? The fix is available on devDeploy and testDeploy.

**Comment by tiusty** [comment]
> This commit fixes the issue: [64105cc](https://github.com/Bebb-Protocol-and-Apps/PWS/commit/64105ccc695a4913cfbde7521b2d60ea60c39b94) I opted for a simple solution by removing the 3D Neighbor visualizations when the menu is opened. Does this seem good to you? The fix is available on devDeploy and testDeploy.

I replied on the other PR. I think it might be better to leave it how it was. Though I could be convinced either way. Hard to know what is better. In the future we might get a better solution than Aframes (such as the previews) so it won't matter

**Review by tiusty — APPROVED** [review]

**Comment by patnorris** [comment]
I've been thinking about a different solution but haven't come up with anything straightforward (as the functionality is spread across multiple Svelte components). I think we can merge this change now but not sure it will last long as the Neighbors will likely get a major redo with upcoming changes (layer 2 integration approach with Bebb using previews)

**Review by tiusty — APPROVED** [review]

**Pull request merged**
