### PR TITLE
Test deploy

### PR DESCRIPTION
**Pull request by patnorris**
All current changes are deployed on the testing stage https://556gz-nyaaa-aaaak-qcjka-cai.icp0.io/ and can be tested there.

These changes include the following PRs:
https://github.com/Bebb-Protocol-and-Apps/PWS/pull/61
https://github.com/Bebb-Protocol-and-Apps/PWS/pull/62
https://github.com/Bebb-Protocol-and-Apps/PWS/pull/64

### CODE REVIEW

**Comment by patnorris** [comment]
My tests via the UI were successful

**Comment by tiusty** [comment]
Tested this and mostly worked. Had some comments in the other PRs

**Comment by tiusty** [comment]
Now when I clicked the hamburger menu it will close the 3D neighbors. Not sure if that is intended. It may be better the other way around.

**Comment by tiusty** [comment]
I will approve this in case that is desired. Otherwise Ideally the neighbor is only removed after you click delete link. Perhaps after clicking delete link when the response is successful, force a reload of the neighbors?

**Review by tiusty — DISMISSED** [review]

**Comment by patnorris** [comment]
I've been thinking about a different solution but haven't come up with anything straightforward (as the functionality is spread across multiple Svelte components). I think we can merge this change now but not sure it will last long as the Neighbors will likely get a major redo with upcoming changes (layer 2 integration approach with Bebb using previews)

**Review by tiusty — DISMISSED** [review]

**Pull request merged**
